# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-24 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0003_calendartoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendartoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
