# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0004_auto_20161224_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendartoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='CalendarToken',
        ),
    ]
