# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-26 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0003_eventenrolment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventenrolment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventenrolment',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='enrolled_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EventEnrolment',
        ),
    ]
