# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-20 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20161220_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
