# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-21 09:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20161220_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='schedule',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='topic',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
    ]
