# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-21 09:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20161221_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='topic',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None),
        ),
    ]
