# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_calendar_calendarevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendarToken',
            new_name='AccessToken',
        ),
    ]
