# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_auto_20170113_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstoken',
            old_name='access_token',
            new_name='accessToken',
        ),
        migrations.RenameField(
            model_name='accesstoken',
            old_name='refresh_token',
            new_name='refreshToken',
        ),
        migrations.RenameField(
            model_name='accesstoken',
            old_name='token_expiry',
            new_name='tokenExpiry',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='calendar_id_g',
            new_name='calendarIdG',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='time_zone',
            new_name='timeZone',
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='calendar_id',
            new_name='calendarId',
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='event_id_g',
            new_name='eventIdG',
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='syncToken',
            field=models.CharField(default=datetime.datetime(2017, 1, 13, 16, 20, 47, 855965, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
    ]
