# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_auto_20170113_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='syncToken',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
