# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_auto_20170113_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
