# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_auto_20170113_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='calendarId',
            new_name='calendar',
        ),
    ]
