# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_auto_20170114_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
