# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-15 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0011_auto_20170115_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
