# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-15 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0012_auto_20170115_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='isSynced',
            field=models.BooleanField(default=False),
        ),
    ]
